'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.17929
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.17929.
'
Namespace SabreCommand
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SabreCommandLLSSoapBinding", [Namespace]:="https://webservices.sabre.com/websvc"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(SignaturePropertiesType)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ManifestType)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(SignatureType)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(Fault)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(Envelope))>  _
    Partial Public Class SabreCommandLLSService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private messageHeaderValueField As MessageHeader
        
        Private securityValueField As Security
        
        Private SabreCommandLLSRQOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New()
            System.Net.ServicePointManager.SecurityProtocol = Net.SecurityProtocolType.Tls12
            Me.Url = Global.GDS_NM_WebServicesSabre.My.MySettings.Default.GDS_NM_WebServicesSabre_AddRemark_AddRemarkService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Property MessageHeaderValue() As MessageHeader
            Get
                Return Me.messageHeaderValueField
            End Get
            Set
                Me.messageHeaderValueField = value
            End Set
        End Property
        
        Public Property SecurityValue() As Security
            Get
                Return Me.securityValueField
            End Get
            Set
                Me.securityValueField = value
            End Set
        End Property
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event SabreCommandLLSRQCompleted As SabreCommandLLSRQCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("MessageHeaderValue", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.InOut),  _
         System.Web.Services.Protocols.SoapHeaderAttribute("SecurityValue", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.InOut),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("OTA", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function SabreCommandLLSRQ(<System.Xml.Serialization.XmlElementAttribute("SabreCommandLLSRQ", [Namespace]:="http://webservices.sabre.com/sabreXML/2003/07")> ByVal SabreCommandLLSRQ1 As SabreCommandLLSRQ) As <System.Xml.Serialization.XmlElementAttribute("SabreCommandLLSRS", [Namespace]:="http://webservices.sabre.com/sabreXML/2003/07")> SabreCommandLLSRS
            Dim results() As Object = Me.Invoke("SabreCommandLLSRQ", New Object() {SabreCommandLLSRQ1})
            Return CType(results(0),SabreCommandLLSRS)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SabreCommandLLSRQAsync(ByVal SabreCommandLLSRQ1 As SabreCommandLLSRQ)
            Me.SabreCommandLLSRQAsync(SabreCommandLLSRQ1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SabreCommandLLSRQAsync(ByVal SabreCommandLLSRQ1 As SabreCommandLLSRQ, ByVal userState As Object)
            If (Me.SabreCommandLLSRQOperationCompleted Is Nothing) Then
                Me.SabreCommandLLSRQOperationCompleted = AddressOf Me.OnSabreCommandLLSRQOperationCompleted
            End If
            Me.InvokeAsync("SabreCommandLLSRQ", New Object() {SabreCommandLLSRQ1}, Me.SabreCommandLLSRQOperationCompleted, userState)
        End Sub
        
        Private Sub OnSabreCommandLLSRQOperationCompleted(ByVal arg As Object)
            If (Not (Me.SabreCommandLLSRQCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SabreCommandLLSRQCompleted(Me, New SabreCommandLLSRQCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.ebxml.org/namespaces/messageHeader"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.ebxml.org/namespaces/messageHeader", IsNullable:=false)>  _
    Partial Public Class MessageHeader
        Inherits System.Web.Services.Protocols.SoapHeader
        
        Private fromField As From
        
        Private toField As [To]
        
        Private cPAIdField As String
        
        Private conversationIdField As String
        
        Private serviceField As Service
        
        Private actionField As String
        
        Private messageDataField As MessageData
        
        Private duplicateEliminationField As Object
        
        Private descriptionField() As Description
        
        Private anyField() As System.Xml.XmlElement
        
        Private idField As String
        
        Private versionField As String
        
        Private anyAttrField() As System.Xml.XmlAttribute
        
        '''<comentarios/>
        Public Property From() As From
            Get
                Return Me.fromField
            End Get
            Set
                Me.fromField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property [To]() As [To]
            Get
                Return Me.toField
            End Get
            Set
                Me.toField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CPAId() As String
            Get
                Return Me.cPAIdField
            End Get
            Set
                Me.cPAIdField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property ConversationId() As String
            Get
                Return Me.conversationIdField
            End Get
            Set
                Me.conversationIdField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Service() As Service
            Get
                Return Me.serviceField
            End Get
            Set
                Me.serviceField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Action() As String
            Get
                Return Me.actionField
            End Get
            Set
                Me.actionField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property MessageData() As MessageData
            Get
                Return Me.messageDataField
            End Get
            Set
                Me.messageDataField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property DuplicateElimination() As Object
            Get
                Return Me.duplicateEliminationField
            End Get
            Set
                Me.duplicateEliminationField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("Description")>  _
        Public Property Description() As Description()
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Qualified, DataType:="ID")>  _
        Public Property id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Qualified)>  _
        Public Property version() As String
            Get
                Return Me.versionField
            End Get
            Set
                Me.versionField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAnyAttributeAttribute()>  _
        Public Property AnyAttr() As System.Xml.XmlAttribute()
            Get
                Return Me.anyAttrField
            End Get
            Set
                Me.anyAttrField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.ebxml.org/namespaces/messageHeader")>  _
    Partial Public Class From
        
        Private partyIdField() As PartyId
        
        Private roleField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("PartyId")>  _
        Public Property PartyId() As PartyId()
            Get
                Return Me.partyIdField
            End Get
            Set
                Me.partyIdField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Role() As String
            Get
                Return Me.roleField
            End Get
            Set
                Me.roleField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.ebxml.org/namespaces/messageHeader")>  _
    Partial Public Class PartyId
        
        Private typeField As String
        
        Private valueField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Qualified)>  _
        Public Property type() As String
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class SignaturePropertyType
        
        Private itemsField() As System.Xml.XmlElement
        
        Private textField() As String
        
        Private targetField As String
        
        Private idField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Items() As System.Xml.XmlElement()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property Target() As String
            Get
                Return Me.targetField
            End Get
            Set
                Me.targetField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>  _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class SignaturePropertiesType
        
        Private signaturePropertyField() As SignaturePropertyType
        
        Private idField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("SignatureProperty")>  _
        Public Property SignatureProperty() As SignaturePropertyType()
            Get
                Return Me.signaturePropertyField
            End Get
            Set
                Me.signaturePropertyField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>  _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class ManifestType
        
        Private referenceField() As ReferenceType
        
        Private idField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("Reference")>  _
        Public Property Reference() As ReferenceType()
            Get
                Return Me.referenceField
            End Get
            Set
                Me.referenceField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>  _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class ReferenceType
        
        Private transformsField() As TransformType
        
        Private digestMethodField As DigestMethodType
        
        Private digestValueField() As Byte
        
        Private idField As String
        
        Private uRIField As String
        
        Private typeField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable:=false)>  _
        Public Property Transforms() As TransformType()
            Get
                Return Me.transformsField
            End Get
            Set
                Me.transformsField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property DigestMethod() As DigestMethodType
            Get
                Return Me.digestMethodField
            End Get
            Set
                Me.digestMethodField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property DigestValue() As Byte()
            Get
                Return Me.digestValueField
            End Get
            Set
                Me.digestValueField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>  _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property URI() As String
            Get
                Return Me.uRIField
            End Get
            Set
                Me.uRIField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property Type() As String
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class TransformType
        
        Private itemsField() As Object
        
        Private textField() As String
        
        Private algorithmField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAnyElementAttribute(),  _
         System.Xml.Serialization.XmlElementAttribute("XPath", GetType(String))>  _
        Public Property Items() As Object()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property Algorithm() As String
            Get
                Return Me.algorithmField
            End Get
            Set
                Me.algorithmField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class DigestMethodType
        
        Private anyField() As System.Xml.XmlNode
        
        Private algorithmField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlTextAttribute(),  _
         System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlNode()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property Algorithm() As String
            Get
                Return Me.algorithmField
            End Get
            Set
                Me.algorithmField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class ObjectType
        
        Private anyField() As System.Xml.XmlNode
        
        Private idField As String
        
        Private mimeTypeField As String
        
        Private encodingField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlTextAttribute(),  _
         System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlNode()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>  _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property MimeType() As String
            Get
                Return Me.mimeTypeField
            End Get
            Set
                Me.mimeTypeField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property Encoding() As String
            Get
                Return Me.encodingField
            End Get
            Set
                Me.encodingField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class SPKIDataType
        
        Private sPKISexpField()() As Byte
        
        Private anyField As System.Xml.XmlElement
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("SPKISexp", DataType:="base64Binary")>  _
        Public Property SPKISexp() As Byte()()
            Get
                Return Me.sPKISexpField
            End Get
            Set
                Me.sPKISexpField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlElement
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class PGPDataType
        
        Private pGPKeyIDField() As Byte
        
        Private pGPKeyPacketField() As Byte
        
        Private anyField() As System.Xml.XmlElement
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property PGPKeyID() As Byte()
            Get
                Return Me.pGPKeyIDField
            End Get
            Set
                Me.pGPKeyIDField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property PGPKeyPacket() As Byte()
            Get
                Return Me.pGPKeyPacketField
            End Get
            Set
                Me.pGPKeyPacketField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class X509IssuerSerialType
        
        Private x509IssuerNameField As String
        
        Private x509SerialNumberField As String
        
        '''<comentarios/>
        Public Property X509IssuerName() As String
            Get
                Return Me.x509IssuerNameField
            End Get
            Set
                Me.x509IssuerNameField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
        Public Property X509SerialNumber() As String
            Get
                Return Me.x509SerialNumberField
            End Get
            Set
                Me.x509SerialNumberField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class X509DataType
        
        Private itemsField() As Object
        
        Private itemsElementNameField() As ItemsChoiceType
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAnyElementAttribute(),  _
         System.Xml.Serialization.XmlElementAttribute("X509CRL", GetType(Byte()), DataType:="base64Binary"),  _
         System.Xml.Serialization.XmlElementAttribute("X509Certificate", GetType(Byte()), DataType:="base64Binary"),  _
         System.Xml.Serialization.XmlElementAttribute("X509IssuerSerial", GetType(X509IssuerSerialType)),  _
         System.Xml.Serialization.XmlElementAttribute("X509SKI", GetType(Byte()), DataType:="base64Binary"),  _
         System.Xml.Serialization.XmlElementAttribute("X509SubjectName", GetType(String)),  _
         System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")>  _
        Public Property Items() As Object()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("ItemsElementName"),  _
         System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ItemsElementName() As ItemsChoiceType()
            Get
                Return Me.itemsElementNameField
            End Get
            Set
                Me.itemsElementNameField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema:=false)>  _
    Public Enum ItemsChoiceType
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlEnumAttribute("##any:")>  _
        Item
        
        '''<comentarios/>
        X509CRL
        
        '''<comentarios/>
        X509Certificate
        
        '''<comentarios/>
        X509IssuerSerial
        
        '''<comentarios/>
        X509SKI
        
        '''<comentarios/>
        X509SubjectName
    End Enum
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class RetrievalMethodType
        
        Private transformsField() As TransformType
        
        Private uRIField As String
        
        Private typeField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable:=false)>  _
        Public Property Transforms() As TransformType()
            Get
                Return Me.transformsField
            End Get
            Set
                Me.transformsField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property URI() As String
            Get
                Return Me.uRIField
            End Get
            Set
                Me.uRIField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property Type() As String
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class RSAKeyValueType
        
        Private modulusField() As Byte
        
        Private exponentField() As Byte
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property Modulus() As Byte()
            Get
                Return Me.modulusField
            End Get
            Set
                Me.modulusField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property Exponent() As Byte()
            Get
                Return Me.exponentField
            End Get
            Set
                Me.exponentField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class DSAKeyValueType
        
        Private pField() As Byte
        
        Private qField() As Byte
        
        Private gField() As Byte
        
        Private yField() As Byte
        
        Private jField() As Byte
        
        Private seedField() As Byte
        
        Private pgenCounterField() As Byte
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property P() As Byte()
            Get
                Return Me.pField
            End Get
            Set
                Me.pField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property Q() As Byte()
            Get
                Return Me.qField
            End Get
            Set
                Me.qField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property G() As Byte()
            Get
                Return Me.gField
            End Get
            Set
                Me.gField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property Y() As Byte()
            Get
                Return Me.yField
            End Get
            Set
                Me.yField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property J() As Byte()
            Get
                Return Me.jField
            End Get
            Set
                Me.jField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property Seed() As Byte()
            Get
                Return Me.seedField
            End Get
            Set
                Me.seedField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property PgenCounter() As Byte()
            Get
                Return Me.pgenCounterField
            End Get
            Set
                Me.pgenCounterField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class KeyValueType
        
        Private itemField As Object
        
        Private textField() As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAnyElementAttribute(),  _
         System.Xml.Serialization.XmlElementAttribute("DSAKeyValue", GetType(DSAKeyValueType)),  _
         System.Xml.Serialization.XmlElementAttribute("RSAKeyValue", GetType(RSAKeyValueType))>  _
        Public Property Item() As Object
            Get
                Return Me.itemField
            End Get
            Set
                Me.itemField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class KeyInfoType
        
        Private itemsField() As Object
        
        Private itemsElementNameField() As ItemsChoiceType1
        
        Private textField() As String
        
        Private idField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAnyElementAttribute(),  _
         System.Xml.Serialization.XmlElementAttribute("KeyName", GetType(String)),  _
         System.Xml.Serialization.XmlElementAttribute("KeyValue", GetType(KeyValueType)),  _
         System.Xml.Serialization.XmlElementAttribute("MgmtData", GetType(String)),  _
         System.Xml.Serialization.XmlElementAttribute("PGPData", GetType(PGPDataType)),  _
         System.Xml.Serialization.XmlElementAttribute("RetrievalMethod", GetType(RetrievalMethodType)),  _
         System.Xml.Serialization.XmlElementAttribute("SPKIData", GetType(SPKIDataType)),  _
         System.Xml.Serialization.XmlElementAttribute("X509Data", GetType(X509DataType)),  _
         System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")>  _
        Public Property Items() As Object()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("ItemsElementName"),  _
         System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ItemsElementName() As ItemsChoiceType1()
            Get
                Return Me.itemsElementNameField
            End Get
            Set
                Me.itemsElementNameField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>  _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema:=false)>  _
    Public Enum ItemsChoiceType1
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlEnumAttribute("##any:")>  _
        Item
        
        '''<comentarios/>
        KeyName
        
        '''<comentarios/>
        KeyValue
        
        '''<comentarios/>
        MgmtData
        
        '''<comentarios/>
        PGPData
        
        '''<comentarios/>
        RetrievalMethod
        
        '''<comentarios/>
        SPKIData
        
        '''<comentarios/>
        X509Data
    End Enum
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class SignatureValueType
        
        Private idField As String
        
        Private valueField() As Byte
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>  _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlTextAttribute(DataType:="base64Binary")>  _
        Public Property Value() As Byte()
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class SignatureMethodType
        
        Private hMACOutputLengthField As String
        
        Private anyField() As System.Xml.XmlNode
        
        Private algorithmField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
        Public Property HMACOutputLength() As String
            Get
                Return Me.hMACOutputLengthField
            End Get
            Set
                Me.hMACOutputLengthField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlTextAttribute(),  _
         System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlNode()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property Algorithm() As String
            Get
                Return Me.algorithmField
            End Get
            Set
                Me.algorithmField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class CanonicalizationMethodType
        
        Private anyField() As System.Xml.XmlNode
        
        Private algorithmField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlTextAttribute(),  _
         System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlNode()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property Algorithm() As String
            Get
                Return Me.algorithmField
            End Get
            Set
                Me.algorithmField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class SignedInfoType
        
        Private canonicalizationMethodField As CanonicalizationMethodType
        
        Private signatureMethodField As SignatureMethodType
        
        Private referenceField() As ReferenceType
        
        Private idField As String
        
        '''<comentarios/>
        Public Property CanonicalizationMethod() As CanonicalizationMethodType
            Get
                Return Me.canonicalizationMethodField
            End Get
            Set
                Me.canonicalizationMethodField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property SignatureMethod() As SignatureMethodType
            Get
                Return Me.signatureMethodField
            End Get
            Set
                Me.signatureMethodField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("Reference")>  _
        Public Property Reference() As ReferenceType()
            Get
                Return Me.referenceField
            End Get
            Set
                Me.referenceField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>  _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class SignatureType
        
        Private signedInfoField As SignedInfoType
        
        Private signatureValueField As SignatureValueType
        
        Private keyInfoField As KeyInfoType
        
        Private objectField() As ObjectType
        
        Private idField As String
        
        '''<comentarios/>
        Public Property SignedInfo() As SignedInfoType
            Get
                Return Me.signedInfoField
            End Get
            Set
                Me.signedInfoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property SignatureValue() As SignatureValueType
            Get
                Return Me.signatureValueField
            End Get
            Set
                Me.signatureValueField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property KeyInfo() As KeyInfoType
            Get
                Return Me.keyInfoField
            End Get
            Set
                Me.keyInfoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("Object")>  _
        Public Property [Object]() As ObjectType()
            Get
                Return Me.objectField
            End Get
            Set
                Me.objectField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>  _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/")>  _
    Partial Public Class detail
        
        Private anyField() As System.Xml.XmlElement
        
        Private anyAttrField() As System.Xml.XmlAttribute
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAnyAttributeAttribute()>  _
        Public Property AnyAttr() As System.Xml.XmlAttribute()
            Get
                Return Me.anyAttrField
            End Get
            Set
                Me.anyAttrField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/")>  _
    Partial Public Class Fault
        
        Private faultcodeField As System.Xml.XmlQualifiedName
        
        Private faultstringField As String
        
        Private faultactorField As String
        
        Private detailField As detail
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property faultcode() As System.Xml.XmlQualifiedName
            Get
                Return Me.faultcodeField
            End Get
            Set
                Me.faultcodeField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property faultstring() As String
            Get
                Return Me.faultstringField
            End Get
            Set
                Me.faultstringField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="anyURI")>  _
        Public Property faultactor() As String
            Get
                Return Me.faultactorField
            End Get
            Set
                Me.faultactorField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property detail() As detail
            Get
                Return Me.detailField
            End Get
            Set
                Me.detailField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/")>  _
    Partial Public Class Body
        
        Private anyField() As System.Xml.XmlElement
        
        Private anyAttrField() As System.Xml.XmlAttribute
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAnyAttributeAttribute()>  _
        Public Property AnyAttr() As System.Xml.XmlAttribute()
            Get
                Return Me.anyAttrField
            End Get
            Set
                Me.anyAttrField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/")>  _
    Partial Public Class Header
        
        Private anyField() As System.Xml.XmlElement
        
        Private anyAttrField() As System.Xml.XmlAttribute
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAnyAttributeAttribute()>  _
        Public Property AnyAttr() As System.Xml.XmlAttribute()
            Get
                Return Me.anyAttrField
            End Get
            Set
                Me.anyAttrField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/")>  _
    Partial Public Class Envelope
        
        Private headerField() As Header
        
        Private bodyField As Body
        
        Private anyField() As System.Xml.XmlElement
        
        Private anyAttrField() As System.Xml.XmlAttribute
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("Header")>  _
        Public Property Header() As Header()
            Get
                Return Me.headerField
            End Get
            Set
                Me.headerField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Body() As Body
            Get
                Return Me.bodyField
            End Get
            Set
                Me.bodyField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAnyAttributeAttribute()>  _
        Public Property AnyAttr() As System.Xml.XmlAttribute()
            Get
                Return Me.anyAttrField
            End Get
            Set
                Me.anyAttrField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.ebxml.org/namespaces/messageHeader")>  _
    Partial Public Class [To]
        
        Private partyIdField() As PartyId
        
        Private roleField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("PartyId")>  _
        Public Property PartyId() As PartyId()
            Get
                Return Me.partyIdField
            End Get
            Set
                Me.partyIdField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Role() As String
            Get
                Return Me.roleField
            End Get
            Set
                Me.roleField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.ebxml.org/namespaces/messageHeader")>  _
    Partial Public Class Service
        
        Private typeField As String
        
        Private valueField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Qualified)>  _
        Public Property type() As String
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.ebxml.org/namespaces/messageHeader")>  _
    Partial Public Class MessageData
        
        Private messageIdField As String
        
        Private timestampField As String
        
        Private refToMessageIdField As String
        
        Private timeToLiveField As Date
        
        Private timeToLiveFieldSpecified As Boolean
        
        Private timeoutField As String
        
        '''<comentarios/>
        Public Property MessageId() As String
            Get
                Return Me.messageIdField
            End Get
            Set
                Me.messageIdField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Timestamp() As String
            Get
                Return Me.timestampField
            End Get
            Set
                Me.timestampField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property RefToMessageId() As String
            Get
                Return Me.refToMessageIdField
            End Get
            Set
                Me.refToMessageIdField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property TimeToLive() As Date
            Get
                Return Me.timeToLiveField
            End Get
            Set
                Me.timeToLiveField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property TimeToLiveSpecified() As Boolean
            Get
                Return Me.timeToLiveFieldSpecified
            End Get
            Set
                Me.timeToLiveFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="nonNegativeInteger")>  _
        Public Property Timeout() As String
            Get
                Return Me.timeoutField
            End Get
            Set
                Me.timeoutField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.ebxml.org/namespaces/messageHeader")>  _
    Partial Public Class Description
        
        Private langField As String
        
        Private valueField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Qualified, [Namespace]:="http://www.w3.org/XML/1998/namespace")>  _
        Public Property lang() As String
            Get
                Return Me.langField
            End Get
            Set
                Me.langField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://schemas.xmlsoap.org/ws/2002/12/secext"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://schemas.xmlsoap.org/ws/2002/12/secext", IsNullable:=false)>  _
    Partial Public Class Security
        Inherits System.Web.Services.Protocols.SoapHeader
        
        Private usernameTokenField As SecurityUsernameToken
        
        Private sabreAthField As String
        
        Private binarySecurityTokenField As String
        
        '''<comentarios/>
        Public Property UsernameToken() As SecurityUsernameToken
            Get
                Return Me.usernameTokenField
            End Get
            Set
                Me.usernameTokenField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property SabreAth() As String
            Get
                Return Me.sabreAthField
            End Get
            Set
                Me.sabreAthField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property BinarySecurityToken() As String
            Get
                Return Me.binarySecurityTokenField
            End Get
            Set
                Me.binarySecurityTokenField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://schemas.xmlsoap.org/ws/2002/12/secext")>  _
    Partial Public Class SecurityUsernameToken
        
        Private usernameField As String
        
        Private passwordField As String
        
        Private newPasswordField() As String
        
        Private organizationField As String
        
        Private domainField As String
        
        '''<comentarios/>
        Public Property Username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("NewPassword")>  _
        Public Property NewPassword() As String()
            Get
                Return Me.newPasswordField
            End Get
            Set
                Me.newPasswordField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Organization() As String
            Get
                Return Me.organizationField
            End Get
            Set
                Me.organizationField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Domain() As String
            Get
                Return Me.domainField
            End Get
            Set
                Me.domainField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://webservices.sabre.com/sabreXML/2003/07")>  _
    Partial Public Class SabreCommandLLSRQ
        
        Private requestField As SabreCommandLLSRQRequest
        
        Private echoTokenField As String
        
        Private timeStampField As String
        
        Private targetField As SabreCommandLLSRQTarget
        
        Private versionField As String
        
        Private sequenceNmbrField As String
        
        Private primaryLangIDField As String
        
        Private altLangIDField As String
        
        Public Sub New()
            MyBase.New
            Me.targetField = SabreCommandLLSRQTarget.Production
        End Sub
        
        '''<comentarios/>
        Public Property Request() As SabreCommandLLSRQRequest
            Get
                Return Me.requestField
            End Get
            Set
                Me.requestField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property EchoToken() As String
            Get
                Return Me.echoTokenField
            End Get
            Set
                Me.echoTokenField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property TimeStamp() As String
            Get
                Return Me.timeStampField
            End Get
            Set
                Me.timeStampField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(),  _
         System.ComponentModel.DefaultValueAttribute(SabreCommandLLSRQTarget.Production)>  _
        Public Property Target() As SabreCommandLLSRQTarget
            Get
                Return Me.targetField
            End Get
            Set
                Me.targetField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Version() As String
            Get
                Return Me.versionField
            End Get
            Set
                Me.versionField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="nonNegativeInteger")>  _
        Public Property SequenceNmbr() As String
            Get
                Return Me.sequenceNmbrField
            End Get
            Set
                Me.sequenceNmbrField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="language")>  _
        Public Property PrimaryLangID() As String
            Get
                Return Me.primaryLangIDField
            End Get
            Set
                Me.primaryLangIDField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="language")>  _
        Public Property AltLangID() As String
            Get
                Return Me.altLangIDField
            End Get
            Set
                Me.altLangIDField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://webservices.sabre.com/sabreXML/2003/07")>  _
    Partial Public Class SabreCommandLLSRQRequest
        
        Private hostCommandField As String
        
        Private outputField As SabreCommandLLSRQRequestOutput
        
        Private mDRSubsetField As String
        
        Private cDATAField As Boolean
        
        Public Sub New()
            MyBase.New
            Me.cDATAField = false
        End Sub
        
        '''<comentarios/>
        Public Property HostCommand() As String
            Get
                Return Me.hostCommandField
            End Get
            Set
                Me.hostCommandField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Output() As SabreCommandLLSRQRequestOutput
            Get
                Return Me.outputField
            End Get
            Set
                Me.outputField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property MDRSubset() As String
            Get
                Return Me.mDRSubsetField
            End Get
            Set
                Me.mDRSubsetField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(),  _
         System.ComponentModel.DefaultValueAttribute(false)>  _
        Public Property CDATA() As Boolean
            Get
                Return Me.cDATAField
            End Get
            Set
                Me.cDATAField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://webservices.sabre.com/sabreXML/2003/07")>  _
    Public Enum SabreCommandLLSRQRequestOutput
        
        '''<comentarios/>
        SCREEN
        
        '''<comentarios/>
        SDS
        
        '''<comentarios/>
        SDSXML
        
        '''<comentarios/>
        DATABAHN
    End Enum
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://webservices.sabre.com/sabreXML/2003/07")>  _
    Public Enum SabreCommandLLSRQTarget
        
        '''<comentarios/>
        Test
        
        '''<comentarios/>
        Production
    End Enum
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://webservices.sabre.com/sabreXML/2003/07")>  _
    Partial Public Class SabreCommandLLSRS
        
        Private responseField As String
        
        Private xML_ContentField As SabreCommandLLSRSXML_Content
        
        Private errorRSField As SabreCommandLLSRSErrorRS
        
        Private echoTokenField As String
        
        Private timeStampField As String
        
        Private targetField As SabreCommandLLSRSTarget
        
        Private versionField As String
        
        Private sequenceNmbrField As String
        
        Private primaryLangIDField As String
        
        Private altLangIDField As String
        
        Public Sub New()
            MyBase.New
            Me.targetField = SabreCommandLLSRSTarget.Production
        End Sub
        
        '''<comentarios/>
        Public Property Response() As String
            Get
                Return Me.responseField
            End Get
            Set
                Me.responseField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property XML_Content() As SabreCommandLLSRSXML_Content
            Get
                Return Me.xML_ContentField
            End Get
            Set
                Me.xML_ContentField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property ErrorRS() As SabreCommandLLSRSErrorRS
            Get
                Return Me.errorRSField
            End Get
            Set
                Me.errorRSField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property EchoToken() As String
            Get
                Return Me.echoTokenField
            End Get
            Set
                Me.echoTokenField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property TimeStamp() As String
            Get
                Return Me.timeStampField
            End Get
            Set
                Me.timeStampField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(),  _
         System.ComponentModel.DefaultValueAttribute(SabreCommandLLSRSTarget.Production)>  _
        Public Property Target() As SabreCommandLLSRSTarget
            Get
                Return Me.targetField
            End Get
            Set
                Me.targetField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Version() As String
            Get
                Return Me.versionField
            End Get
            Set
                Me.versionField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="nonNegativeInteger")>  _
        Public Property SequenceNmbr() As String
            Get
                Return Me.sequenceNmbrField
            End Get
            Set
                Me.sequenceNmbrField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="language")>  _
        Public Property PrimaryLangID() As String
            Get
                Return Me.primaryLangIDField
            End Get
            Set
                Me.primaryLangIDField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="language")>  _
        Public Property AltLangID() As String
            Get
                Return Me.altLangIDField
            End Get
            Set
                Me.altLangIDField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://webservices.sabre.com/sabreXML/2003/07")>  _
    Partial Public Class SabreCommandLLSRSXML_Content
        
        Private anyField() As System.Xml.XmlElement
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://webservices.sabre.com/sabreXML/2003/07")>  _
    Partial Public Class SabreCommandLLSRSErrorRS
        
        Private errorsField As SabreCommandLLSRSErrorRSErrors
        
        '''<comentarios/>
        Public Property Errors() As SabreCommandLLSRSErrorRSErrors
            Get
                Return Me.errorsField
            End Get
            Set
                Me.errorsField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://webservices.sabre.com/sabreXML/2003/07")>  _
    Partial Public Class SabreCommandLLSRSErrorRSErrors
        
        Private errorField As SabreCommandLLSRSErrorRSErrorsError
        
        '''<comentarios/>
        Public Property [Error]() As SabreCommandLLSRSErrorRSErrorsError
            Get
                Return Me.errorField
            End Get
            Set
                Me.errorField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://webservices.sabre.com/sabreXML/2003/07")>  _
    Partial Public Class SabreCommandLLSRSErrorRSErrorsError
        
        Private errorInfoField As SabreCommandLLSRSErrorRSErrorsErrorErrorInfo
        
        Private errorCodeField As String
        
        Private severityField As String
        
        Private errorMessageField As String
        
        '''<comentarios/>
        Public Property ErrorInfo() As SabreCommandLLSRSErrorRSErrorsErrorErrorInfo
            Get
                Return Me.errorInfoField
            End Get
            Set
                Me.errorInfoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property ErrorCode() As String
            Get
                Return Me.errorCodeField
            End Get
            Set
                Me.errorCodeField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Severity() As String
            Get
                Return Me.severityField
            End Get
            Set
                Me.severityField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property ErrorMessage() As String
            Get
                Return Me.errorMessageField
            End Get
            Set
                Me.errorMessageField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://webservices.sabre.com/sabreXML/2003/07")>  _
    Partial Public Class SabreCommandLLSRSErrorRSErrorsErrorErrorInfo
        
        Private messageField As String
        
        '''<comentarios/>
        Public Property Message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://webservices.sabre.com/sabreXML/2003/07")>  _
    Public Enum SabreCommandLLSRSTarget
        
        '''<comentarios/>
        Test
        
        '''<comentarios/>
        Production
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub SabreCommandLLSRQCompletedEventHandler(ByVal sender As Object, ByVal e As SabreCommandLLSRQCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SabreCommandLLSRQCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As SabreCommandLLSRS
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),SabreCommandLLSRS)
            End Get
        End Property
    End Class
End Namespace
