'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funcionalidad para autoguardar de My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")>  _
        Public ReadOnly Property Servicios_SessionCreateRQ_SessionCreateRQService() As String
            Get
                Return CType(Me("Servicios_SessionCreateRQ_SessionCreateRQService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")>  _
        Public ReadOnly Property Servicios_SessionClose_SessionCloseRQService() As String
            Get
                Return CType(Me("Servicios_SessionClose_SessionCloseRQService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")>  _
        Public ReadOnly Property Servicios_TravelItineraryRead_TravelItineraryReadService() As String
            Get
                Return CType(Me("Servicios_TravelItineraryRead_TravelItineraryReadService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")>  _
        Public ReadOnly Property Servicios_AirTicket_AirTicketService() As String
            Get
                Return CType(Me("Servicios_AirTicket_AirTicketService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")>  _
        Public ReadOnly Property Servicios_IgnoreTransaction_IgnoreTransactionService() As String
            Get
                Return CType(Me("Servicios_IgnoreTransaction_IgnoreTransactionService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")>  _
        Public ReadOnly Property Servicios_EndTransaction_EndTransactionService() As String
            Get
                Return CType(Me("Servicios_EndTransaction_EndTransactionService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")>  _
        Public ReadOnly Property Servicios_SabreCommand_SabreCommandLLSService() As String
            Get
                Return CType(Me("Servicios_SabreCommand_SabreCommandLLSService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")>  _
        Public ReadOnly Property Servicios_QueueAccess_QueueAccessService() As String
            Get
                Return CType(Me("Servicios_QueueAccess_QueueAccessService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")>  _
        Public ReadOnly Property Servicios_DailySalesReport_DailySalesReportService() As String
            Get
                Return CType(Me("Servicios_DailySalesReport_DailySalesReportService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")>  _
        Public ReadOnly Property Servicios_OTA_Cancel_OTA_CancelService() As String
            Get
                Return CType(Me("Servicios_OTA_Cancel_OTA_CancelService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")>  _
        Public ReadOnly Property Servicios_Mileage_MileageService() As String
            Get
                Return CType(Me("Servicios_Mileage_MileageService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")>  _
        Public ReadOnly Property Servicios_TicketCoupon_eTicketCouponService() As String
            Get
                Return CType(Me("Servicios_TicketCoupon_eTicketCouponService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")>  _
        Public ReadOnly Property GDS_NM_WebServicesSabre_ContextChange_ContextChangeService() As String
            Get
                Return CType(Me("GDS_NM_WebServicesSabre_ContextChange_ContextChangeService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")>  _
        Public ReadOnly Property GDS_NM_WebServicesSabre_AddRemark_AddRemarkService() As String
            Get
                Return CType(Me("GDS_NM_WebServicesSabre_AddRemark_AddRemarkService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")>  _
        Public ReadOnly Property GDS_NM_WebServicesSabre_SpecialService_SpecialServiceService() As String
            Get
                Return CType(Me("GDS_NM_WebServicesSabre_SpecialService_SpecialServiceService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")>  _
        Public ReadOnly Property GDS_NM_WebServicesSabre_DeleteSpecialService_DeleteSpecialServiceService() As String
            Get
                Return CType(Me("GDS_NM_WebServicesSabre_DeleteSpecialService_DeleteSpecialServiceService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")>  _
        Public ReadOnly Property GDS_NM_WebServicesSabre_ARUNK_ARUNK_Service() As String
            Get
                Return CType(Me("GDS_NM_WebServicesSabre_ARUNK_ARUNK_Service"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")>  _
        Public ReadOnly Property GDS_NM_WebServicesSabre_OTA_AirPrice_OTA_AirPriceService() As String
            Get
                Return CType(Me("GDS_NM_WebServicesSabre_OTA_AirPrice_OTA_AirPriceService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")>  _
        Public ReadOnly Property GDS_NM_WebServicesSabre_PromotionalShopping_PromotionalService() As String
            Get
                Return CType(Me("GDS_NM_WebServicesSabre_PromotionalShopping_PromotionalService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")>  _
        Public ReadOnly Property GDS_NM_WebServicesSabre_RulesFromPrice_RulesFromPriceService() As String
            Get
                Return CType(Me("GDS_NM_WebServicesSabre_RulesFromPrice_RulesFromPriceService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")>  _
        Public ReadOnly Property GDS_NM_WebServicesSabre_TravelItineraryAddInfo_TravelItineraryAddInfoService() As String
            Get
                Return CType(Me("GDS_NM_WebServicesSabre_TravelItineraryAddInfo_TravelItineraryAddInfoService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")>  _
        Public ReadOnly Property GDS_NM_WebServicesSabre_TravelItineraryModifyInfo_TravelItineraryModifyInfoService() As String
            Get
                Return CType(Me("GDS_NM_WebServicesSabre_TravelItineraryModifyInfo_TravelItineraryModifyInfoServic"& _ 
                    "e"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")>  _
        Public ReadOnly Property GDS_NM_WebServicesSabre_InvoiceItinerary_InvoiceItineraryService() As String
            Get
                Return CType(Me("GDS_NM_WebServicesSabre_InvoiceItinerary_InvoiceItineraryService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")>  _
        Public ReadOnly Property GDS_NM_WebServicesSabre_Fare_FareService() As String
            Get
                Return CType(Me("GDS_NM_WebServicesSabre_Fare_FareService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")>  _
        Public ReadOnly Property GDS_NM_WebServicesSabre_OTA_AirRules_OTA_AirRulesService() As String
            Get
                Return CType(Me("GDS_NM_WebServicesSabre_OTA_AirRules_OTA_AirRulesService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")>  _
        Public ReadOnly Property GDS_NM_WebServicesSabre_DesignatePrinter_DesignatePrinterService() As String
            Get
                Return CType(Me("GDS_NM_WebServicesSabre_DesignatePrinter_DesignatePrinterService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")>  _
        Public ReadOnly Property GDS_NM_WebServicesSabre_OTA_AirBookLLS200_OTA_AirBookService() As String
            Get
                Return CType(Me("GDS_NM_WebServicesSabre_OTA_AirBookLLS200_OTA_AirBookService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")>  _
        Public ReadOnly Property GDS_NM_WebServicesSabre_DailyEMD_Report_DailyEMD_ReportService() As String
            Get
                Return CType(Me("GDS_NM_WebServicesSabre_DailyEMD_Report_DailyEMD_ReportService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")>  _
        Public ReadOnly Property GDS_NM_WebServicesSabre_VoidTicket_VoidTicketService() As String
            Get
                Return CType(Me("GDS_NM_WebServicesSabre_VoidTicket_VoidTicketService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com")>  _
        Public ReadOnly Property GDS_NM_WebServicesSabre_TravelItineraryReadRQ_TravelItineraryReadService() As String
            Get
                Return CType(Me("GDS_NM_WebServicesSabre_TravelItineraryReadRQ_TravelItineraryReadService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")>  _
        Public ReadOnly Property GDS_NM_WebServicesSabre_EMD_Display_EMD_DisplayService() As String
            Get
                Return CType(Me("GDS_NM_WebServicesSabre_EMD_Display_EMD_DisplayService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com")>  _
        Public ReadOnly Property GDS_NM_WebServicesSabre_TravelItineraryReadRQ360_TravelItineraryReadService() As String
            Get
                Return CType(Me("GDS_NM_WebServicesSabre_TravelItineraryReadRQ360_TravelItineraryReadService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")>  _
        Public ReadOnly Property GDS_NM_WebServicesSabre_ModifyRemark_ModifyRemarkService() As String
            Get
                Return CType(Me("GDS_NM_WebServicesSabre_ModifyRemark_ModifyRemarkService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")>  _
        Public ReadOnly Property GDS_NM_WebServicesSabre_AutomatedExchanges_AutomatedExchangesService() As String
            Get
                Return CType(Me("GDS_NM_WebServicesSabre_AutomatedExchanges_AutomatedExchangesService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")>  _
        Public ReadOnly Property GDS_NM_WebServicesSabre_ExchangeShopping_ExchangeShoppingService() As String
            Get
                Return CType(Me("GDS_NM_WebServicesSabre_ExchangeShopping_ExchangeShoppingService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")>  _
        Public ReadOnly Property GDS_NM_WebServicesSabre_AirTicketLLS270_AirTicketService() As String
            Get
                Return CType(Me("GDS_NM_WebServicesSabre_AirTicketLLS270_AirTicketService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")>  _
        Public ReadOnly Property GDS_NM_WebServicesSabre_DisplayPriceQuote_DisplayPriceQuoteService() As String
            Get
                Return CType(Me("GDS_NM_WebServicesSabre_DisplayPriceQuote_DisplayPriceQuoteService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")>  _
        Public ReadOnly Property GDS_NM_WebServicesSabre_AirTicketLLS230_AirTicketService() As String
            Get
                Return CType(Me("GDS_NM_WebServicesSabre_AirTicketLLS230_AirTicketService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")>  _
        Public ReadOnly Property GDS_NM_WebServicesSabre_QueuePlaceLLS204_QueuePlaceService() As String
            Get
                Return CType(Me("GDS_NM_WebServicesSabre_QueuePlaceLLS204_QueuePlaceService"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.GDS_NM_WebServicesSabre.My.MySettings
            Get
                Return Global.GDS_NM_WebServicesSabre.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
